# **4.TO - DO - Task**

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
def convert(value, unit):
    conversions = {
        "m": (value * 3.28, "ft"),
        "ft": (value / 3.28, "m"),
        "kg": (value * 2.204, "lbs"),
        "lbs": (value / 2.204, "kg"),
        "L": (value * 0.264, "gal"),
        "gal": (value / 0.264, "L")
    }
    return conversions.get(unit, (None, None))

def main():
  print("Converter")
  print("1. Length(m to ft or ft to m)")
  print("2. Weight(kg to lbs or lbs to kg)")
  print("3. Volume (L to ga or gal to L)")

  try:
    choice = int(input("Choose connversion (1-3):"))
    if choice not in [1, 2, 3]:
          print("Invalid choice.")
          return
    value = float (input("Enter the value to convert:"))
    if choice == 1:
      unit = input("Enter unit ('m' or 'ft'): ")
    elif choice ==2:
      unit = input("Enter unit ('kg' or 'ft': ): ")
    elif choice == 3:
      unit = input("Enter unit ('L' or 'gal': ): ")
    else:
      print("Invlid number.")
      return

    result , new_unit = convert(value, unit)

    if result is None:
        print("Invalid unit entered.")
    else:
        print(f"{value} {unit} is equal to {result:.2f} {new_unit}")

  except ValueError:
        print("Error: Please enter a valid numeric value.")

if __name__ == "__main__":
    main()


Converter
1. Length(m to ft or ft to m)
2. Weight(kg to lbs or lbs to kg)
3. Volume (L to ga or gal to L)
Choose connversion (1-3):1
Enter the value to convert:10
Enter unit ('m' or 'ft'): m
10.0 m is equal to 32.80 ft


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [49]:
def addition(numbers):
  return sum(numbers)

def average(numbers):
  if len(numbers) == 0:
    return 0
  return sum(numbers) / len(numbers)

def maximum(numbers):
  return max(numbers)

def minimum(numbers):
  return min(numbers)

def main():
  print("Choose the option: ")
  print("1. Sum")
  print("2. Average")
  print("3. Maximum")
  print("4. Minimum")

  try:
    choice = int(input("Enter the choice (1-4): "))
    if choice not in [1, 2, 3, 4]:
      print("Invalid choice. Please enter a number between 1 and 4.")
      return

    numbers = input("Enter a list of numbers separated by spaces: ").split()
    if len(numbers) == 0:
      print("Error: Please enter at least one number.")
      return

    try:
      number_list = [float(num) for num in numbers]
    except ValueError:
      print("Error: Please enter a valid list of numbers.")
      return

    if choice == 1:
      result = addition(number_list)
      print(f"The sum of the numbers is: {result}")

    elif choice == 2:
      result = average(number_list)
      print(f"The average of the numbers is: {result}")

    elif choice == 3:
      result = maximum(number_list)
      print(f"The maximum of the numbers is: {result}")
    elif choice == 4:
      result = minimum(number_list)
      print(f"The minimum of the numbers is: {result}")

  except ValueError:
    print("Error: Please enter a valid number choice.")

if __name__ == "__main__":
  main()


Choose the option: 
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the choice (1-4): 1
Enter a list of numbers separated by spaces: 1 2 3 4 5
The sum of the numbers is: 15.0


4.2 Exercise on List Manipulation:

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].


In [ ]:
def extract_every_other(lst):
    """Extract every other element from the list, starting from the first element."""
    return lst[::2]

def main():
    input_str = input("Enter a list of numbers separated by spaces: ")

    input_list = [int(item) for item in input_str.split()]

    output_list = extract_every_other(input_list)

    print(f"Output: {output_list}")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 1 2 3 4 6
Output: [1, 3, 6]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].


In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

def main():
    input_str = input("Enter a list of numbers separated by spaces: ")
    input_list = [int(item) for item in input_str.split()]

    try:
        start = int(input("Enter the starting index: "))
        end = int(input("Enter the ending index: "))

        """ Checking if the indices are within a valid range"""
        if start < 0 or end < 0 or start >= len(input_list) or end >= len(input_list):
            print("Error: Invalid indices.")
            return

        """Getting the sublist"""
        sublist = get_sublist(input_list, start, end)
        print(f"Output: {sublist}")

    except ValueError:
        print("Error: Please enter valid integers for indices.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Enter the starting index: 1
Enter the ending index: 3
Output: [2, 3, 4]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """Return a reversed list using slicing."""
    return lst[::-1]

input_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(input_list)
print(f"Reversed list: {reversed_list}")


Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove(lst):
  return lst[1:-1]

input_list = [2,4,6,8,10]
output_list = remove(input_list)
print(f"Output: {output_list}")

Output: [4, 6, 8]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].


In [ ]:
def get_first_n(lst, n):
  return lst[:n]

input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)
print(f"Output: {output_list}")


Output: [1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing. • Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].


In [ ]:
def get_last_n(lst, n):
    """Return the last n elements of the list using slicing."""
    return lst[-n:]

def main():
    input_str = input("Enter a list of numbers separated by spaces: ")
    input_list = [int(item) for item in input_str.split()]

    try:
        n = int(input("Enter n: "))

        if n > len(input_list) or n <= 0:
            print("Error: n must be greater than 0 and less than or equal to the length of the list.")
            return

        resulting_sublist = get_last_n(input_list, n)
        print(f"The last {n} elements are: {resulting_sublist}")

    except ValueError:
        print("Error: Please enter valid integers.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Enter n: 2
The last 2 elements are: [5, 6]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1]. 20


In [ ]:
def reverse_skip(lst):
  return lst[-2::-2]
input_list = [1,2,3,4,5,6,7,8]
result = reverse_skip(input_list)
print(f"Elements in reverse order skipping the digits: {result}")

Elements in reverse order skipping the digits: [7, 5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].


In [ ]:
def flatten(lst):
    """Flatten a nested list into a single list."""
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(flatten(sublist))  # Recursive call for the nested lists
        else:
            flat_list.append(sublist)
    return flat_list

# Example usage
input_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(input_list)
print(f"Flattened list: {flattened_list}")


Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices. • Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.



In [ ]:
def access_nested_element(lst, indices):
  for index in indices:
    lst = lst[index] #updating lst to tthe sublist at the current index
  return lst  #Return the element at the final index

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
element = access_nested_element(nested_list, indices)
print(f"Accessed element: {element}")

Accessed element: 6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth). • Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.


In [ ]:
def sum_nested(lst):
  total =0
  for item in lst:
    if isinstance(item, list): # If the item is a list, recursively sum its elements
      total += sum_nested(item)
    else:
      total += item # If it's a number, add it to the total
  return total
nested_list = [[1, 2], [3, [4, 5]], 6]
total_sum = sum_nested(nested_list)
print(f"Sum of all elements: {total_sum}")


Sum of all elements: 21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list. • Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].


In [ ]:
def remove_element(lst, elem):
  result = []
  for item in lst:
    if isinstance(item, list):
      result.append(remove_element(item,elem))
    else:
      if item != elem:
        result.append(item)
  return result

nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 3
modified_list = remove_element(nested_list, element_to_remove)
print(f"Modified list: {modified_list}")

Modified list: [[1, 2], [2], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth). • Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6. 21


In [ ]:
def find_max(lst):
  max_element= float('-inf') #starting with the smallest possible value

  for item in lst:
    if isinstance(item, list):  # If the item is a sublist, recurse into it
      max_element = max(max_element, find_max(item))
    else:
      max_element = max(max_element, item)
  return max_element

nested_list = [[1, 2], [3, [4, 5]], 6]
maximum_value = find_max(nested_list)
print(f"Maximum value in the nested list: {maximum_value}")

Maximum value in the nested list: 6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list. • Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.


In [ ]:
def count_occurence(lst, elem):
  count=0

  for item in lst:
    if isinstance(item, list): # if the item is the sub list , recurse into it
      count += count_occurence(item, elem)
    else:
      if item ==elem:
        count+= 1
  return count

nested_list = [[1, 2], [2, 3], [2, 4]]
element = 2
occurrences = count_occurence(nested_list, element)
print(f"Occurrences of {element} in the nested list: {occurrences}")

Occurrences of 2 in the nested list: 3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth. • Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].


In [ ]:
def deep_faltten(lst):
  flattened = []

  for item in lst:
    if isinstance(item, list):
      flattened.extend(deep_faltten(item))
    else:
      flattened.append(item)
  return flattened

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flattened_list = deep_faltten(nested_list)
print("Flattened list:", flattened_list)

Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


 Nested List Average:

Write a Python function that calculates the average of all elements in a nested list. • Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5. 22


In [1]:
def deep_faltten(lst):
  flattened = []

  for item in lst:
    if isinstance(item, list):
      flattened.extend(deep_faltten(item))
    else:
      flattened.append(item)
  return flattened


def average_nested(lst):
  flattened_list = deep_faltten(lst)
  total = sum(flattened_list)
  return total / len(flattened_list)

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
average = average_nested(nested_list)
print(f"Average: {average}")

Average: 4.5


# 10 To - Do - NumPy
Please complete all the problems listed below:


10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full} 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like} 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like} 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [2]:
import numpy as np

In [3]:
# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):")
print(empty_array)

Empty Array (2x2):
[[2.6340442e-316 0.0000000e+000]
 [1.4821969e-323            nan]]


In [4]:
# 2. Initialize an all-one array with size 4X2
ones_array = np.ones((4,2))
print("All Ones Array (4*2)")
print(ones_array)

All Ones Array (4*2)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
# 3. Return a new array of given shape and type, filled with a fill value
new_array = np.full((3, 3), 7)
print("New Array (3x3):")
print(new_array)

New Array (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [6]:
# 4. Return a new array of zeros with the same shape and type as a given array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_array = np.zeros_like(existing_array)
print("Zeros Array:")
print(zeros_array)

Zeros Array:
[[0 0 0]
 [0 0 0]]


In [7]:
#Return a new array of ones with the same shape and type as a given array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])
ones_array = np.ones_like(existing_array)
print("Ones Array:")
print(ones_array)

Ones Array:
[[1 1 1]
 [1 1 1]]


In [8]:
# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("NumPy Array:")
print(numpy_array)

NumPy Array:
[1 2 3 4]


Problem - 2:

Array Manipulation: Numerical Ranges and Array indexing: Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values. 6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [9]:
# 1. Create an array with values ranging from 10 to 49
array = np.arange(10, 50)
print("Array 10-49: ")
print(array)

Array 10-49: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print("3x3 Matrix:")
print(matrix)

3x3 Matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array:")
print(random_array)
print("Mean of the Array:", mean_value)

Random Array:
[0.43635282 0.34580164 0.32971694 0.69951912 0.20915341 0.48636428
 0.3803045  0.0570571  0.59756148 0.77840961 0.68250823 0.16921892
 0.35301278 0.9564082  0.12582779 0.68752164 0.37468311 0.88356628
 0.77934534 0.54582645 0.06430842 0.94453664 0.48538381 0.26885698
 0.37319206 0.21666489 0.09380129 0.96279659 0.51039458 0.24669389]
Mean of the Array: 0.4681596263015771


In [17]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_array = np.random.random((10, 10))
min_value = random_array.min()
max_value = random_array.max()
print(random_array)
print(f"Minimum value: {min_value}, Maximum value: {max_value}")

[[0.44605159 0.76447123 0.24121983 0.10001365 0.24787632 0.82545615
  0.73564086 0.72331577 0.52077353 0.09400507]
 [0.00674739 0.11735767 0.09811625 0.60689889 0.6787846  0.35833992
  0.5417146  0.05306044 0.28058129 0.32821865]
 [0.63318242 0.74493096 0.10095072 0.04494014 0.98324605 0.98165051
  0.33304594 0.50872109 0.82331352 0.46096187]
 [0.82707965 0.35422304 0.14941146 0.39212986 0.79902203 0.44416738
  0.15166066 0.78137865 0.81813592 0.63141381]
 [0.07031654 0.80010165 0.90280989 0.60559374 0.59679439 0.80953644
  0.50819653 0.05603645 0.16576056 0.64891664]
 [0.738537   0.48341653 0.65945768 0.09520935 0.95941917 0.87496066
  0.12116978 0.71407964 0.21563538 0.23044006]
 [0.59022494 0.2200284  0.62767363 0.87310186 0.28475516 0.06323508
  0.73344589 0.97417995 0.62120898 0.62588575]
 [0.22594481 0.27406598 0.15469438 0.62124906 0.91535908 0.76660187
  0.40541942 0.70784581 0.14152843 0.00946841]
 [0.96090742 0.94116709 0.57803403 0.70247879 0.37469996 0.47941095
  0.88532811

In [18]:
# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [20]:
# 8. Create a 2d array with 1 on border and 0 inside
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard pattern:")
print(checkerboard)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [27]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#Add the two array.
add_result = x + y
print("Addition of x and y:")
print(add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print("\nSubtraction of x and y:")
print(subtract_result)

# 3. Multiply the array with any integers of your choice (e.g., multiply x by 2)
multiply_result = x * 2
print("\nMultiplication of x by 2:")
print(multiply_result)

# 4. Find the square of each element of the array
square_res = np.square(x)
print("\nSquare of each element in x:")
print(square_res)

# 5. Find the dot product between v and w:
dot_vw = np.dot(v,w)
print("\nDot product of v and w:")
print(dot_vw)

dot_xv = np.dot(x,v)
print("\nDot product of x and v:")
print(dot_xv)

dot_xy = np.dot(x,y)
print("\nDot product of x and y:")
print(dot_xy)

# Concatenate x(and)y along row and Concatenate v(and)w along column.
conc_xy = np.concatenate((x,y), axis=0)
print("\nConcatenation of x and y along rows:")
print(conc_xy)

conc_vw = np.concatenate((v.reshape(-1,1),w.reshape(-1,1)), axis=1)
print("\nConcatenation of v and w along column:")
print(conc_vw)

# 7. Concatenate x and v; if you get an error, observe and explain why you got the error?
try:
  concat_xv = np.concatenate((x,v), axis=0)
  print("\n COncatenate x and v along row: ")
  print(concat_xv)
except ValueError as e:
  print(f"Error: {e}")

Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplication of x by 2:
[[ 2  4]
 [ 6 10]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along column:
[[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT.
• Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func tion of Numpy}


In [35]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A−1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("I:")
print(I)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:")
print(AB)
print("\nBA:")
print(BA)

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = np.dot(A, B).T
B_transpose = B.T
A_transpose = A.T
B_transpose_A_transpose = np.dot(B_transpose, A_transpose)
print("\n(AB)^T:")
print(AB_transpose)
print("\nB^T * A^T: ")
print(B_transpose_A_transpose)


# Solving the system of linear equations using Inverse Method
# Given system of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system in matrix form: AX = B
A_eq = np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B_eq = np.array([-1,-3,9])

#A (A^-1)
X = np.dot(np.linalg.inv(A_eq), B_eq)
print("\nSolution for x, y,z: ")
print(X)



I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T: 
[[23 51]
 [13 29]]

Solution for x, y,z: 
[ 2.  1. -2.]


1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [39]:
import time

list1 = [i for i in range(1,1000001)]
list2 = [i for i in range(1000001,2000001)]

"""Measurring the time for element wisw addition"""
start_time = time.time()
result_time = [a+b for a,b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for element-wise addition: {list_time} seconds")


#COnvert list ot numpy array
array1 = np.array(list1)
array2 = np.array(list2)

# measuring time for element-wisw addition using numpy arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise addition using numpy arrays: {array_time} seconds")


Time taken for element-wise addition: 0.2426915168762207 seconds
Time taken for element-wise addition using numpy arrays: 0.0026454925537109375 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [40]:
list1 = [i for i in range(1,1000001)]
list2 = [i for i in range(1000001,2000001)]

"""Measurring the time for element wise multiplication"""
start_time = time.time()
result_time = [a*b for a,b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for element-wise multiplication: {list_time} seconds")


array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise multiplication using numpy arrays: {array_time} seconds")

Time taken for element-wise multiplication: 0.06143617630004883 seconds
Time taken for element-wise multiplication using numpy arrays: 0.005585908889770508 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.



In [41]:
list1 = [i for i in range(1,1000001)]
list2 = [i for i in range(1000001,2000001)]

start_time = time.time()
result_time = [a*b for a,b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for element-wise multiplication: {list_time} seconds")

array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for dot product using NumPy arrays: {array_time:.6f} seconds")

Time taken for element-wise multiplication: 0.08801126480102539 seconds
Time taken for dot product using NumPy arrays: 0.001853 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea sure and print the time taken for this operation.
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


In [48]:
# size of matrix
N=1000

matrix1 = [[i + j for j in range(N)] for i in range(N)]
matrix2 = [[i - j for j in range(N)] for i in range(N)]

def matrix_multiply(A,B):
  result = [[0] *N for _ in range(N)]
  for i in range(N):
    for j in range(N):
      for k in range(N):
        result[i][j] += A[i][k] * B[k][j]
  return result
start_time = time.time()
result = matrix_multiply(matrix1, matrix2)
end_time = time.time()
execute_time = end_time - start_time
print(f"Time taken for matrix multiplication: {execute_time} seconds")

array1 = np.array(matrix1)
array2 = np.array(matrix2)

start_time = time.time()
result_numpy = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for matrix multiplication using NumPy: {numpy_time:.6f} seconds")

Time taken for matrix multiplication: 182.4498074054718 seconds
Time taken for matrix multiplication using NumPy: 1.242108 seconds
